storage:
  filesystems:
    - mount:
        device: /dev/disk/by-id/google-gadgets-persistent
        format: ext4
  files:
    - filesystem: root
      path: /opt/startup-script/startup-script
      contents:
        inline: |
          #!/usr/bin/env bash
          export DOCKER_CLIENT_TIMEOUT=120
          && export COMPOSE_HTTP_TIMEOUT=120
          && mkdir -p /run/startup \
          && cd /run/startup \
          && git clone https://github.com/acomagu/gadgets \
          && cd gadgets \
          && docker run -i google/cloud-sdk gcloud kms decrypt --location global --keyring gadgets --key docker-compose_secret_yml --ciphertext-file - --plaintext-file - <docker-compose.secret.yml.enc >docker-compose.secret.yml \
          && docker run -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:$PWD -w $PWD docker/compose:1.23.2 -fdocker-compose.{yml,secret.yml,gce.yml} up
      mode: 0755
      user:
        id: 500
      group:
        id: 500
systemd:
  units:
    # Create swap
    - name: var-vm-swapfile1.swap
      enabled: true
      contents: |
        [Unit]
        Description=Turn on swap
        Requires=create-swapfile.service
        After=create-swapfile.service

        [Swap]
        What=/var/vm/swapfile1

        [Install]
        WantedBy=multi-user.target
    - name: create-swapfile.service
      contents: |
        [Unit]
        Description=Create a swapfile
        RequiresMountsFor=/var
        ConditionPathExists=!/var/vm/swapfile1

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/mkdir -p /var/vm
        ExecStart=/usr/bin/fallocate -l 4g /var/vm/swapfile1
        ExecStart=/usr/bin/chmod 600 /var/vm/swapfile1
        ExecStart=/usr/sbin/mkswap /var/vm/swapfile1
        RemainAfterExit=true
    # Mount external disk
    - name: mnt-disks-gadgets\x2dpersistent.mount
      enabled: true
      contents: |
        [Mount]
        What=/dev/disk/by-id/google-gadgets-persistent
        Where=/mnt/disks/gadgets-persistent
        Type=ext4

        [Install]
        RequiredBy=local-fs.target
    # Startup script
    - name: startup-script.service
      enabled: true
      contents: |
        [Unit]
        Requires=mnt-disks-gadgets\x2dpersistent.mount
        Wants=network-online.target
        After=network-online.target

        [Service]
        ExecStart=/opt/startup-script/startup-script

        [Install]
        WantedBy=multi-user.target
