version: '3'
services:
  abccal:
    build: abccal
    expose:
      - '80'
  dicebot:
    image: acomagu/dicebot
  graphdb:
    image: acomagu/graphdb:8.8.1-free
    expose:
      - '7200'
    command: ['-Dgraphdb.home=/opt/graphdb/home', '-Xms128m', '-Xmx128m']
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
