version: '3'
services:
  musicbot:
    image: goodcodingfriends/musicbot
  dicebot:
    image: acomagu/dicebot
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
